app/views/layouts/homepage.html.erb, app/views/shared/_footer.html.erb, config/locales/hyrax.en.yml
Updated header, footer, and logo
=> basic UI customization

app/assets/javascripts/oasis.js, app/views/records/edit_fields/_comments.html.erb, app/views/records/edit_fields/_of_likely_interest_to.html.erb, app/views/records/edit_fields/_participants_domain_of_use.html.erb, app/views/records/edit_fields/_summary_notes.html.erb
=> Issue 53 upload forms improvments

app/models/concerns/oasis/oasis_metadata.rb, app/views/records/edit_fields/_participants_age.html.erb, config/authorities/age_of_learners.yml
=> Issue 45 make age of learners as checkboxes

app/assets/javascripts/application.js, app/assets/javascripts/oasis.js, app/controllers/catalog_controller.rb, app/controllers/oasis_authority_mapping.rb, app/helpers/apa.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/helpers/blacklight/render_constraints_helper_behavior.rb, app/models/concerns/oasis/oasis_metadata.rb, app/views/_controls.html.erb, app/views/_user_util_links.html.erb, app/views/catalog/_homepage_search_form.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, app/views/hyrax/homepage/_recently_uploaded.html.erb, app/views/hyrax/homepage/index.html.erb, app/views/records/edit_fields/_comments.html.erb, app/views/records/edit_fields/_of_likely_interest_to.html.erb, app/views/records/edit_fields/_participants_age.html.erb, app/views/records/edit_fields/_participants_domain_of_use.html.erb, app/views/records/edit_fields/_summary_notes.html.erb, config/authorities/age_of_learners.yml, config/routes.rb
=> Issue 41 remove static aboutpage

app/controllers/oasis_authority_mapping.rb, app/helpers/apa.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/helpers/blacklight/render_constraints_helper_behavior.rb, app/models/concerns/oasis/oasis_metadata.rb, app/views/catalog/_index_list_default.html.erb, app/views/records/edit_fields/_participants_age.html.erb, config/authorities/age_of_learners.yml
=> Issue 35 search result page

app/assets/javascripts/oasis.js, app/controllers/catalog_controller.rb, app/controllers/oasis_authority_mapping.rb, app/helpers/apa.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/helpers/blacklight/render_constraints_helper_behavior.rb, app/models/concerns/oasis/oasis_metadata.rb, app/views/_controls.html.erb, app/views/_user_util_links.html.erb, app/views/catalog/_homepage_search_form.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, app/views/hyrax/homepage/_recently_uploaded.html.erb, app/views/hyrax/homepage/index.html.erb, app/views/records/edit_fields/_comments.html.erb, app/views/records/edit_fields/_of_likely_interest_to.html.erb, app/views/records/edit_fields/_participants_age.html.erb, app/views/records/edit_fields/_participants_domain_of_use.html.erb, app/views/records/edit_fields/_summary_notes.html.erb, config/authorities/age_of_learners.yml
=> Issue 54 35 more value validations on homepage and search result page

.gitignore, app/assets/javascripts/oasis.js, app/assets/stylesheets/oasis.css, app/controllers/catalog_controller.rb, app/controllers/oasis_authority_mapping.rb, app/forms/hyrax/summary_form.rb, app/helpers/apa.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/helpers/blacklight/render_constraints_helper_behavior.rb, app/models/concerns/oasis/oasis_metadata.rb, app/views/_controls.html.erb, app/views/_user_util_links.html.erb, app/views/catalog/_homepage_search_form.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, app/views/hyrax/homepage/_recently_uploaded.html.erb, app/views/hyrax/homepage/index.html.erb, app/views/records/edit_fields/_comments.html.erb, app/views/records/edit_fields/_of_likely_interest_to.html.erb, app/views/records/edit_fields/_participants_age.html.erb, app/views/records/edit_fields/_participants_domain_of_use.html.erb, app/views/records/edit_fields/_summary_notes.html.erb, config/authorities/age_of_learners.yml
=> Issue 63 visibility problem

.gitignore, app/assets/javascripts/oasis.js, app/assets/stylesheets/oasis.css, app/controllers/catalog_controller.rb, app/controllers/oasis_authority_mapping.rb, app/forms/hyrax/summary_form.rb, app/helpers/apa.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/helpers/blacklight/render_constraints_helper_behavior.rb, app/models/concerns/oasis/oasis_metadata.rb, app/views/_controls.html.erb, app/views/_user_util_links.html.erb, app/views/catalog/_homepage_search_form.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, app/views/hyrax/homepage/_recently_uploaded.html.erb, app/views/hyrax/homepage/index.html.erb, app/views/records/edit_fields/_comments.html.erb, app/views/records/edit_fields/_of_likely_interest_to.html.erb, app/views/records/edit_fields/_participants_age.html.erb, app/views/records/edit_fields/_participants_domain_of_use.html.erb, app/views/records/edit_fields/_summary_notes.html.erb, config/authorities/age_of_learners.yml, config/authorities/participant_types.yml, config/routes.rb
=> Issue 68 incorrect fields search result page

.gitignore, app/assets/javascripts/oasis.js, app/assets/stylesheets/oasis.css, app/controllers/catalog_controller.rb, app/controllers/oasis_authority_mapping.rb, app/forms/hyrax/summary_form.rb, app/helpers/apa.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/helpers/blacklight/render_constraints_helper_behavior.rb, app/models/concerns/oasis/oasis_metadata.rb, app/views/_controls.html.erb, app/views/_user_util_links.html.erb, app/views/catalog/_homepage_search_form.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, app/views/hyrax/homepage/_recently_uploaded.html.erb, app/views/hyrax/homepage/index.html.erb, app/views/records/edit_fields/_comments.html.erb, app/views/records/edit_fields/_of_likely_interest_to.html.erb, app/views/records/edit_fields/_participants_age.html.erb, app/views/records/edit_fields/_participants_domain_of_use.html.erb, app/views/records/edit_fields/_participants_firstlanguage.html.erb, app/views/records/edit_fields/_summary_notes.html.erb, config/authorities/age_of_learners.yml, config/authorities/participant_types.yml, config/routes.rb
=> Issue 77 wrong page numbers

app/controllers/oasis_authority_mapping.rb, app/views/_controls.html.erb, app/views/hyrax/admin/workflows/index.html.erb, app/views/hyrax/base/show.html.erb, app/views/records/edit_fields/_participants_age.html.erb
=> Issue 82 no method error in admin workflows

app/controllers/oasis_authority_mapping.rb, app/views/_controls.html.erb, app/views/hyrax/admin/workflows/index.html.erb, app/views/hyrax/base/_cite_summary.erb, app/views/hyrax/base/show.html.erb, app/views/records/edit_fields/_participants_age.html.erb
=> Issue 98 writer of summary order

app/views/hyrax/base/_cite_summary.erb, config/locales/hyrax.en.yml
=> Issue 97 author writer text update

.gitignore, .solr_wrapper, Gemfile, Gemfile.lock, config/blacklight.yml, config/database.yml, config/fedora.yml, config/initializers/figaro.rb, config/secrets.yml, config/solr.yml
Introduce more secure secrets management. In addtion it harmonise different dev enviroment.
=> Add Figaro for secrets management

config/environments/production.rb, config/initializers/hyrax.rb, config/initializers/mailboxer.rb
Add SMTP configuration as required by #42
=> Customise contact form and configure email notification

.travis.yml
fixed travis ci build problem, introduced by figaro
=> add travis ci configuration

app/views/hyrax/base/_materials_on_iris.html.erb
=> Show IRIS URL if present 

lib/tasks/thumbnails.rake
=> Add rake task to refresh thumbnails dates

config/initializers/hyrax.rb
Use configure/application.yml to pass information about Google Analytics tracker ID.
=> Use Figaro for google analytics id

config/environments/production.rb, config/initializers/hyrax.rb
Will handle correctly true/false values and symbol :debug
=> Improve figaro production varaiable

Gemfile, Gemfile.lock
=> Add production gems

Gemfile, Gemfile.lock
=> update sinatra to fix the security vulnerability

app/assets/javascripts/oasis.js, app/forms/hyrax/summary_form.rb, app/views/hyrax/base/_publication.html.erb, app/views/hyrax/base/_summary_writer.html.erb, app/views/hyrax/base/show.html.erb, app/views/records/edit_fields/_publication_author_all.html.erb, app/views/records/edit_fields/_summary_writer_all.html.erb, spec/features/publication_author_order_spec.rb, spec/features/summary_writer_order_spec.rb
=> Issue 150 author display order

app/search_builders/oasis/oasis_search_builder.rb
add 3 new 'other' fields to Solr search parameters
=> add 'other' fields into search parameters

app/views/devise/registrations/new.html.erb
Add additional terms and conditions to signup page.
=> Issue 156 terms in signup page

app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/mailboxer.rb, config/locales/mailboxer.en.yml
Resolve #151 and #152 
- Add approving and managing roles
- Add workflows with those roles
- Submitted work for approval can't be edit
See this [google document](https://docs.google.com/document/d/1g9dnq7cLXqFqWEBiQjZRNEe63EeISe3dSYxPjTP676I/edit?usp=sharing) for feature documentation.
=> Add submission workflow

app/services/hyrax/workflow/abstract_notification.rb, app/services/hyrax/workflow/changes_required_notification.rb, app/services/hyrax/workflow/deposited_notification.rb, app/services/hyrax/workflow/pending_review_notification.rb, app/views/hyrax/base/_workflow_actions.html.erb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/locales/hyrax.en.yml
Fix #204 
- Define oasis_host variable used with document_url to construct full URL in notification emails. 
- Improve notification messages readability
- Correct bug with "Review and Approve" section jumping form bottom to middle page.
=> Issue 204 - improve notification emails

config/authorities/participant_types.yml, config/authorities/research_areas.yml
Update keyword labels for topic and participant type. As described in #248
=> update keyword labels

app/helpers/apa.rb, app/helpers/summary_apa.rb
=> fix display bug for summaries with 'other' journals

app/views/hyrax/summaries/_show_summary.html.erb
Add notes field to summary show page.
=> add notes field to summary details page

app/controllers/survey_controller.rb
- Fix email params misconfiguraiton
=> Correct params hash name

config/environments/production.rb
Correct default log level behaviour. 
Use :info.
Resolve #258
=> Correct default log level

app/views/survey/new.html.erb
simple text and text position changes on the downloader survey page
=> Issue 44 further text change download survey

app/views/survey/new.html.erb
Request for additional minor change to text of Downloader survey. After this changes are ready to be deployed to live service
Resolves#44
=> Change case of oasis to OASIS

app/controllers/hyrax/pages_controller.rb, app/models/content_block.rb, app/views/_controls.html.erb, app/views/hyrax/homepage/_alerts.html.erb, app/views/hyrax/pages/_form.html.erb, config/locales/hyrax.en.yml, config/routes.rb
Resolves #290 and #291 
- New Supporting Journal tab page that can be editable
- Replace email link with Mailchimp service
=> Resolve issue 290 and 291:  Add link and new tab

app/views/_controls.html.erb, app/views/hyrax/content_blocks/templates/supporting_journals.html.erb
Follow up to #291 
- reorder tab order
- add new menu template
=> Reorder menu tabs

app/views/hyrax/summaries/_show_summary.html.erb
Notes field disappeared with #275
=> Reinstate notes field

config/authorities/journals.yml
=> add new journal: Journal of Language, Identity & Education

config/locales/hyrax.en.yml
Change activities tab label to 'Dissemination'
=> change activities tab label

Dockerfile, Gemfile.lock, README.md, docker-compose.yml, docker/docker-entrypoint-web.sh
- Use Ruby 2.6.6
- Use Bundler 2.1.6
- Use PostgresSQL v12
- Small improvements to build process
=> Refresh docker local development

app/assets/javascripts/oasis.js
It's better to move tinymce code to the end of oasis.js
=> move tinymce code to the end of oasis.js

app/assets/javascripts/application.js, app/assets/javascripts/oasis.js
Run oasis.js on turbolinks:load event
=> Use turbolinks

Gemfile, Gemfile.lock, db/schema.rb
Use v1.2.3
Update db schema to PG flavour
=> Bum up pg gem

app/assets/javascripts/behaviours/iris_url.js, app/assets/javascripts/behaviours/journal_name.js, app/assets/javascripts/behaviours/tinymce_init.js, app/assets/javascripts/oasis.js
- TinyMCE init loads on edit opening page
- Jurnal 'other' field consistent behaviour
- IRIS URL consistent behaviour
=> Fix JS bugs

app/views/_controls.html.erb, app/views/hyrax/pages/_form.html.erb, config/locales/hyrax.en.yml, config/routes.rb
Rename journal tab
Rename URL jurnal path
=> Rename journals tab

app/views/hyrax/pages/_form.html.erb
Hyrax form works with old URL only.
=> Revert back some URL change

app/views/hyrax/homepage/_alerts.html.erb, app/views/hyrax/homepage/index.html.erb
Resolves [DSD-12](https://dti-uoy.atlassian.net/browse/DSD-12)
=> Add citation and user survey

app/views/hyrax/homepage/_alerts.html.erb
=> Main page small changes

app/assets/stylesheets/hyrax.scss, app/assets/stylesheets/oasis.css, app/views/hyrax/base/_cite_summary.erb, app/views/hyrax/base/_publication.html.erb, app/views/hyrax/base/_title_of_summary.erb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, app/views/hyrax/summaries/_show_summary.html.erb, config/locales/hyrax.en.yml, docker/docker-entrypoint-web.sh
=> Lan 14/summary details page

app/assets/javascripts/behaviours/accordion_links.js, app/assets/javascripts/oasis.js
- Resolve #287 and [LAN-5](https://dti-uoy.atlassian.net/browse/LAN-5)
- Close accordion tabs on /concernt/summaris and /help pages
- For #hash links allow opening selected tab e.g. for /help/#3 open 3rd accordion tab on help page.
=> LAN-5 - open accordion tab with links

app/assets/stylesheets/oasis.css, app/views/hyrax/file_sets/media_display/_pdf.html.erb
Change survey ID to avoid fire-ing GA event
=> Fix LAN-44 / GA no_set value on data-events

app/assets/stylesheets/oasis.css, app/views/hyrax/base/_generic_field_with_authority.html.erb
Resolve SF00093932
- Dispal authority field values alphabetically.
- Improve summary details UX
=> Order summary keywords display

app/assets/javascripts/behaviours/title_hebrew.js
Resolves [LAN-51 ](https://dti-uoy.atlassian.net/browse/LAN-51) - Change Hebrew text direction flow from left to right
- title on the details page 
- title as presented on search result
=> feature/lan-51 Direction of title with Hebrew text

app/views/hyrax/homepage/_alerts.html.erb
=> Fix SF-00150945 request

lib/tasks/clean_users.rake
Add rake task to clean none admin users as per [SF-0230610](https://uoy.lightning.force.com/lightning/r/Case/5004K00000KqcVOQAZ/view)
=> Resolve SF-0230610

app/views/hyrax/summaries/_show_summary.html.erb
Resolve [sf-00226607](https://uoy.lightning.force.com/lightning/r/Case/5004K00000KpMhEQAV/view)
=> Fix broken accordion on mobile devices

app/views/hyrax/base/_generic_field_with_authority.html.erb
- Resolves [SF-00287368](https://uoy.lightning.force.com/lightning/r/Case/5004K00000O4b0EQAR/view) 
- List Other values as separate ```<li>```
=> Resolves SF-00287368

lib/tasks/subscription.rake
Add rake task to generate sumaries.json file consumed weekly by OASIS Subscription service
=> add summaries export script

config/authorities/research_areas.yml
Issues: Added in none alphabetical order
=> Add new terms at research area

lib/tasks/subscription.rake
=> Subscription task

app/assets/javascripts/hyrax/ga_events.js, app/views/_ga.html.erb
Resolves JIRA [LAN-61](https://dti-uoy.atlassian.net/browse/LAN-61)
=> Upgrade GA to use Google Tag Manager

app/assets/javascripts/application.js
=> security: upgrade jQuery
